# Site settings
title: John Morrow
email: me@jmo.mx
description: > # this means to ignore newlines until "baseurl:"
  My personal website and blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmo.mx" # the base hostname & protocol for your site

#usernames
twitter_username: mrjohnmorrow
github_username:  mrjohnmorrow
linkedin_username: jmomx
facebook_username: mrjohnmorrow
#dribbble_username: johnmorrow

#visual options
permalink: pretty


# Build settings
markdown: kramdown
